### ISSUE TITLE
Ported to Node

### ISSUE THREAD

**Issue by josher19** [seansullivan/markov-php#1]
Hi Sean,

Ported your Markov PHP code to Node and added some inline-documentation.
https://github.com/josher19/markov

Could probably be combined with [Faker-Phil](https://github.com/josher19/Faker-Phil) to generate random websites and fake user data.

Best Regards,
Josh Weinstein

**Comment by seansullivan** [comment]
Thanks Josh.  This indeed looks useful to have in the Node.js domain!
